name: Deployment Status Comment
on: [deployment_status]
jobs:
  comment:
    runs-on: ubuntu-latest
    if: github.event.deployment.environment == 'staging' && github.event.deployment_status.state == 'success'
    steps:
      - run: >
          curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" "https://api.github.com/repos/jfine-sandbox/testing-deployments/pulls?head=jfine-sandbox:jfine-patch-1&state=open" | jq -r ".[0].comments_url"
      - run: >
          curl -X POST 
          -H "Accept: application/vnd.github+json" 
          -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" 
          -d '{"body":"Here's the performance suite results!"}'
          https://api.github.com/repos/jfine-sandbox/testing-deployments/issues/2/comments
