name: Deployment Comment
on: [deployment]
jobs:
  Staging-Deployment-Comment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Create a comment
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/1/comments -d '{"body":"Staging deploy"}'
  Production-Deployment-Comment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Create a comment
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/1/comments -d '{"body":"Production deploy"}'
