name: Deployment
concurrency: staging
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - run: echo "This would be a deploy or something"
