name: Deployment Comment
on: [deployment]
jobs:
  Deployment-Comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create a comment
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/1/comments -d '{"body":"Me too"}'
