name: Deployment Status Comment
on:
  - deployment_status
jobs:
  comment:
    runs-on: ubuntu-latest
    if: github.event.deployment.environment == 'staging' && github.event.deployment_status.state == 'success'
    steps:
      - run: >
          curl -X POST 
          -H "Accept: application/vnd.github+json" 
          -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" 
          https://api.github.com/repos/${{github.repository}}/issues/1/comments
          -d '{"body":"${{github.event.deployment_status.state}} and ${{github.event.deployment.ref}}"}'
