name: Deployment Comment
on:
  - deployment
jobs:
  Staging-Deployment-Comment:
    runs-on: ubuntu-latest
    steps:
    - name: Deployment Comment
      run: echo "github.ref ${{github.ref}} github.ref_name ${{github.ref_name}} github.event.deployment.enviroment ${{github.event.deployment.enviroment}}"
